
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: miao
  password: 88740
  host: localhost

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog

production:
  <<: *default
  database: blog