:concurrency: 5
:timeout: 30
:verbose: false
:dynamic: true
:enabled: false
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [notifications, 100]
  - [default, 3]
  - [scheduler, 10]
  - [group, 5]
